### ISSUE TITLE
Chapter 2 - code for vertical tangent fix looks wrong

### ISSUE THREAD

**Issue by smileymi6** [jimmysong/programmingbitcoin#119]
Whats the point of the "* self.x" here if 0 * anything is 0? 

`if self == other and self.y == 0 * self.x:  (1)`

**Comment by chanhosuh** [comment]
I would guess it's done this way as a quickie way to get around the fact that you can't just do `self.y == 0` as the left-hand-side is a field element and the right-hand-side is an integer.  You would need to do something like `self.y.num == 0`.

At this point in the book, I don't believe the above excerpt should work, as scalar multiplication hasn't been defined yet.

**Comment by smileymi6** [comment]
OK, but at the end of chapter 2 he's only using real numbers, and as you say when he moves into Chapter 3 and starts using FieldElements this doesn't work anyway, so its a confusing way of teaching this IMO.

**Comment by chanhosuh** [comment]
I agree it's confusing.  Looks like Jimmy copied over the code from the `ecc` module in the next chapter.

As a way of avoiding confusion, it may be better for the text to just make a remark explaining conceptually how to fix the vertical tangent issue and make a reference to the next chapter.

**Comment by chiranz** [comment]
That might be a typo. This is what he actually meant.
<pre>
`if self == other and self.y == 0:
     return self.__class__(None, None, self.a, self.b)`
<pre>

**Comment by jimmysong** [comment]
You can't do self.y == 0 when you start subclassing with FieldElement (which starts happening in chapter 3), hence the 0* self.x (making it possible for us to pass in FieldElements for x and y instead of real numbers). It's kludgy and I'm not exactly happy about it, but the alternative is to use a class attribute like "zero" or something. 

I'll definitely try to explain this better in the next edition. Thanks everyone!
