### ISSUE TITLE
Chapter2.ipynb line 2: ValueError: (-1, -2) is not on the curve

### ISSUE THREAD

**Issue by bnonni** [jimmysong/programmingbitcoin#229]
I'm getting this error "out of the box" when starting chapter 2. I thought the book would explain why and how to fix it, but I don't see that in the book. Anyone else having this problem? Am I supposed to fix this? Any guidance would be great. Thanks.

![image](https://user-images.githubusercontent.com/19941207/141369891-45cae658-e079-4b67-b418-51b3d438f048.png)

**Comment by anipy1** [comment]
Hello @bnonni , In #<1> we're checking that the point is actually on the curve or not.
Since the P1(x,y,a,b) = (-1,-1,5,7) and P2(x,y,a,b)=(-1,-2,5,7).

## For P1
LHS = y^2 = (-1)^2 = 1
RHS = `x^3 + a*x + b` = `(-1)^3 + (5*-1) + 7` = 1
Therefore, LHS == RHS

## For P2
LHS = y^2 = (-2)^2 = 4
RHS = `x^3 + a*x + b` = `(-1)^3 + (5*-1) + 7` = 1
Therefore, LHS != RHS

> (-1,-2) is not on the curve

Hope that helps.

**Comment by bnonni** [comment]
@aniketambore thanks for that explanation. I understand the math, but I found it confusing that the jupyter notebook was programmed to throw an error by default when previous exercises/examples would represent something similar (i.e. that LHS != RHS, etc.) by using a boolean expression/comparison or by asking us (the user) to write some code to resolve the error. Nonetheless, thank you for clarifying and reinforcing the math behind the lesson 👍🏻
