### ISSUE TITLE
Chapter 1: Question about Finite Field Division

### ISSUE THREAD

**Issue by jachiang** [jimmysong/programmingbitcoin#8]
Hi @jimmysong,
 Quick question regarding chapter 1: finite field division

From my understanding.
We derive Fermat: `n^(p-1)%p=1 where p is prime`

Then, we use Fermat's theorem to evaluate finite field division:
`b^-1 = b^-1 ⋅ 1 = b^-1 ⋅ b^(p-1) = b^(p-2)`

I don't follow this part: `b^-1 ⋅ b^(p-1) = b^(p-2)`
Here, exponents (-1, p-1) are added up, like in normal math. However, some of the exponents, such as -1, are negative and therefore represent division, which we, at this point are still in the process of defining.

Why is it possible to perform normal arithmetic on negative exponents?

Thanks in advance!

**Comment by smh69** [comment]
I'll give it a shot jachiang, mostly to help clear my own mind, let me know if this makes sense.

b^-1 is just 1/b being multiplied to both sides of the equation b^(p-1) = 1,
effectively giving us (b^(p-1))/b = 1/b, which is exactly what we want... except we still cannot divide.

But since we can multiply, and pow(), we're just going to multiply b by itself one less time.  If b^(p-1) gives us 1, then b^(p-2) will give u 1/b, our multiplicative inverse, which we can use without dividing.

certainly for large primes, we'll never have a negative exponent to deal with, no real division.

Im totally lost on what to say about field of prime=2 {0,1}, we'd get 0^0 = 1 and 1^0 = 1, and my explanation falls apart. ;(

**Comment by jimmysong** [comment]
We're defining b^-1 more than anything else. Division doesn't have meaning until you say it's the inverse of multiplication. To figure out the value analytically, you end up having to use Fermat's Little Theorem and get the b^(p-2)
